/**
 * Seed formations ABJ — Catalogue officiel
 * Source : Catalogue ABJ 2025-26 + site academiedebijouteriejoaillerie.fr
 * 40 formations officielles avec codes longs (codes utilisés en production/n8n)
 *
 * Note : equipementRequis est renseigné pour les formations courtes.
 * Les formations longues (CAP_ATBJ) gèrent leurs équipements via le mapping n8n.
 */

import prisma from '../src/lib/prisma'

const formations = [
  // ============================================================
  // CAP
  // ============================================================
  {
    codeFormation: 'CAP_ATBJ',
    nom: 'CAP Art et Techniques de la Bijouterie-Joaillerie (option bijouterie-joaillerie)',
    categorie: 'CAP',
    dureeHeures: 800,
    dureeJours: null,
    niveauRequis: 'Niveau Baccalauréat',
    diplomeDelivre: 'CAP Art et Techniques de la Bijouterie-Joaillerie',
    tarifStandard: 15000,
    description: 'Cursus de 1 an de septembre à juin. Financement tout public. Formation en présentiel préparant au diplôme d\'État CAP ATBJ option bijouterie-joaillerie.',
    prerequis: ['Niveau Baccalauréat', 'Entretien de sélection', 'Test technique'],
    objectifs: [
      'Maîtriser les techniques de base de la bijouterie-joaillerie',
      'Concevoir et réaliser des bijoux',
      'Obtenir le CAP ATBJ',
    ],
    programme: 'Bijouterie technique, joaillerie, sertissage, dessin technique, dessin gouaché, histoire de l\'art du bijou, gestion d\'entreprise. 800h en présentiel sur 10 mois.',
    equipementRequis: [],
  },

  // ============================================================
  // BIJOUTERIE DE CRÉATEUR
  // ============================================================
  {
    codeFormation: 'BIJ_CREATEUR_N1',
    nom: 'Bijouterie de créateur sur métal — Niveau 1',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage abordant les techniques de base en bijouterie de créateur. Apprentissage des postures, gestuelles et techniques fondamentales.',
    prerequis: [],
    objectifs: [
      'Découvrir les techniques de base de la bijouterie créateur',
      'Réaliser une première pièce',
    ],
    programme: 'Techniques de base en bijouterie sur métal, outillage, postures et gestuelles professionnelles.',
    equipementRequis: [],
  },
  {
    codeFormation: 'BIJ_CREATEUR_N2',
    nom: 'Bijouterie de créateur sur métal — Niveau 2',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Approfondissement des techniques de bijouterie de créateur sur métal.',
    prerequis: ['Niveau 1 ou compétences équivalentes'],
    objectifs: [
      'Approfondir les techniques de bijouterie créateur',
      'Réaliser des pièces plus complexes',
    ],
    programme: 'Techniques intermédiaires en bijouterie sur métal.',
    equipementRequis: [],
  },
  {
    codeFormation: 'BIJ_CREATEUR_N3',
    nom: 'Bijouterie de créateur sur métal — Niveau 3',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveaux 1 et 2 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Perfectionnement avancé en bijouterie de créateur sur métal.',
    prerequis: ['Niveaux 1 et 2 ou compétences équivalentes'],
    objectifs: ['Maîtriser les techniques avancées de bijouterie créateur'],
    programme: 'Techniques avancées en bijouterie sur métal.',
    equipementRequis: [],
  },

  // ============================================================
  // BIJOUTERIE TECHNIQUE
  // ============================================================
  {
    codeFormation: 'BIJ_TECHNIQUE_N1',
    nom: 'Bijouterie technique sur métal — Niveau 1',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage approfondissant les techniques avancées en bijouterie technique.',
    prerequis: [],
    objectifs: ['Acquérir les techniques de bijouterie technique'],
    programme: 'Techniques avancées de bijouterie sur métal.',
    equipementRequis: [],
  },
  {
    codeFormation: 'BIJ_TECHNIQUE_N2',
    nom: 'Bijouterie technique sur métal — Niveau 2',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Approfondissement des techniques avancées en bijouterie technique.',
    prerequis: ['Niveau 1 ou compétences équivalentes'],
    objectifs: ['Approfondir les techniques de bijouterie technique'],
    programme: 'Techniques intermédiaires-avancées de bijouterie sur métal.',
    equipementRequis: [],
  },
  {
    codeFormation: 'BIJ_TECHNIQUE_N3',
    nom: 'Bijouterie technique sur métal — Niveau 3',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveaux 1 et 2 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Maîtrise des techniques avancées en bijouterie technique.',
    prerequis: ['Niveaux 1 et 2 ou compétences équivalentes'],
    objectifs: ['Maîtriser les techniques avancées de bijouterie technique'],
    programme: 'Techniques avancées de bijouterie sur métal — niveau expert.',
    equipementRequis: [],
  },

  // ============================================================
  // JOAILLERIE
  // ============================================================
  {
    codeFormation: 'JOAILLERIE_N1',
    nom: 'Joaillerie — Niveau 1',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage abordant les techniques de base en joaillerie.',
    prerequis: [],
    objectifs: ['Découvrir les techniques fondamentales de la joaillerie'],
    programme: 'Initiation à la joaillerie : outillage, techniques de base, montage sur métal précieux.',
    equipementRequis: [],
  },
  {
    codeFormation: 'JOAILLERIE_N2',
    nom: 'Joaillerie — Niveau 2',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Approfondissement des techniques de joaillerie.',
    prerequis: ['Niveau 1 ou compétences équivalentes'],
    objectifs: ['Approfondir les techniques de joaillerie'],
    programme: 'Techniques intermédiaires de joaillerie.',
    equipementRequis: [],
  },
  {
    codeFormation: 'JOAILLERIE_N3',
    nom: 'Joaillerie — Niveau 3',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveaux 1 et 2 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Maîtrise des techniques avancées de joaillerie.',
    prerequis: ['Niveaux 1 et 2 ou compétences équivalentes'],
    objectifs: ['Maîtriser les techniques avancées de joaillerie'],
    programme: 'Techniques avancées de joaillerie.',
    equipementRequis: [],
  },

  // ============================================================
  // HAUTE FANTAISIE
  // ============================================================
  {
    codeFormation: 'HF_N1',
    nom: 'Haute fantaisie — Niveau 1',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 950,
    description: 'Enfilage de perle, tissage, nœuds, etc. Introduction aux techniques de haute fantaisie.',
    prerequis: [],
    objectifs: ['Maîtriser les techniques de base de la haute fantaisie'],
    programme: 'Enfilage de perles, techniques de tissage, réalisation de nœuds.',
    equipementRequis: [],
  },
  {
    codeFormation: 'HF_N2',
    nom: 'Haute fantaisie — Niveau 2',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 950,
    description: 'Approfondissement des techniques de haute fantaisie.',
    prerequis: ['Niveau 1 ou compétences équivalentes'],
    objectifs: ['Approfondir les techniques de haute fantaisie'],
    programme: 'Techniques intermédiaires de haute fantaisie.',
    equipementRequis: [],
  },
  {
    codeFormation: 'HF_N3',
    nom: 'Haute fantaisie — Niveau 3',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveaux 1 et 2 ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 950,
    description: 'Maîtrise avancée des techniques de haute fantaisie.',
    prerequis: ['Niveaux 1 et 2 ou compétences équivalentes'],
    objectifs: ['Maîtriser les techniques avancées de haute fantaisie'],
    programme: 'Techniques avancées de haute fantaisie.',
    equipementRequis: [],
  },

  // ============================================================
  // MAQUETTE DE BIJOUX
  // ============================================================
  {
    codeFormation: 'MAQUETTE_N1',
    nom: 'Maquette de Bijoux — Niveau 1 Initiation',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage d\'initiation aux techniques de base en maquette en bijouterie-joaillerie. Modélisation en cire et Plastiline.',
    prerequis: ['Débutants acceptés', 'CV', 'Questionnaire de positionnement'],
    objectifs: [
      'Découvrir les matériaux de maquette (cire, Plastiline)',
      'Réaliser des volumes simples',
      'Comprendre le lien entre maquette et bijou final',
    ],
    programme: 'Initiation maquette : matériaux (cire dure, cire souple, Plastiline), outils, réalisation de volumes géométriques, initiation à l\'interprétation de volumes.',
    equipementRequis: ['etabli', 'outils_cire'],
  },
  {
    codeFormation: 'MAQUETTE_N2',
    nom: 'Maquette de Bijoux — Niveau 2 Perfectionnement',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: 'Niveau 1 maquette ou expérience équivalente',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage de perfectionnement en maquette de bijoux. Réalisation de formes complexes et préparation pour la fonte.',
    prerequis: ['Avoir suivi le niveau 1 ou justifier d\'une expérience équivalente'],
    objectifs: [
      'Réaliser des volumes organiques complexes',
      'Maîtriser les techniques de jonction et assemblage en cire',
      'Préparer une maquette pour la fonte à cire perdue',
    ],
    programme: 'Perfectionnement maquette : formes organiques, assemblages complexes, préparation des jets de coulée, introduction à la fonte à cire perdue.',
    equipementRequis: ['etabli', 'outils_cire'],
  },
  {
    codeFormation: 'MAQUETTE_N3',
    nom: 'Maquette de Bijoux — Niveau 3 Avancé',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: 'Niveau 2 maquette ou expérience équivalente',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage avancé en maquette de bijoux. Réalisations complexes et projets professionnels en cire.',
    prerequis: ['Avoir suivi le niveau 2 ou justifier d\'une expérience équivalente'],
    objectifs: [
      'Réaliser des projets maquette complexes',
      'Maîtriser la sculpture de précision en cire',
      'Créer des prototypes professionnels',
    ],
    programme: 'Maquette avancée : sculpture de précision, projets créateurs complets, réalisation d\'un prototype professionnel en cire prêt à la fonte.',
    equipementRequis: ['etabli', 'outils_cire'],
  },

  // ============================================================
  // CAO/DAO
  // ============================================================
  {
    codeFormation: 'CAO_DAO',
    nom: 'CAO Appliquée à la Bijouterie — Initiation',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 26,
    dureeJours: 4,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 910,
    description: 'Formation en modélisation 3D appliquée à la bijouterie. Distanciel : séance d\'introduction et d\'installation de 2h + 24h de cours. Logiciels de CAO/DAO spécialisés bijouterie (type MatrixGold, Rhino...).',
    prerequis: [
      'Débutants acceptés',
      'Ordinateur personnel compatible',
      'CV',
      'Questionnaire de positionnement',
    ],
    objectifs: [
      'Maîtriser les outils de modélisation 3D dédiés à la bijouterie',
      'Créer des bijoux en 3D sur ordinateur',
      'Préparer des fichiers pour l\'impression 3D ou la FAO',
    ],
    programme: 'Formation distanciel : installation du logiciel (2h), modélisation 3D (24h) : interface, outils de base, création de volumes, bagues, pendentifs, application des textures et matières, export pour impression 3D.',
    equipementRequis: ['ordinateur', 'logiciel_cao'],
  },

  // ============================================================
  // SERTISSAGE
  // ============================================================
  {
    codeFormation: 'SERTI_N1',
    nom: 'Sertissage — Niveau 1 Serti Clos',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage d\'initiation au sertissage, technique du serti clos. Apprentissage des outils et gestes fondamentaux du sertisseur.',
    prerequis: ['Débutants acceptés', 'CV', 'Questionnaire de positionnement'],
    objectifs: [
      'Confectionner les outils du sertisseur (échoppe, onglet)',
      'Maîtriser le serti clos taille ronde et ovale',
      'Comprendre les principes de base du sertissage',
    ],
    programme: 'Initiation sertissage : confection des outils (échoppe, onglet), serti clos taille ronde, serti clos taille ovale.',
    equipementRequis: ['etabli_sertissage', 'outils_sertissage', 'microscope'],
  },
  {
    codeFormation: 'SERTI_N2',
    nom: 'Sertissage — Niveau 2 Serti Griffes',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: 'Niveau 1 serti clos ou expérience équivalente',
    diplomeDelivre: null,
    tarifStandard: 1230,
    description: 'Stage de perfectionnement en sertissage, technique du serti griffes. Mise en valeur des pierres par les griffes.',
    prerequis: ['Avoir suivi le niveau 1 (serti clos) ou justifier d\'une expérience équivalente'],
    objectifs: [
      'Maîtriser le serti griffes',
      'Travailler différentes formes de pierres',
      'Affiner la précision du sertissage',
    ],
    programme: 'Perfectionnement sertissage : serti griffes, différentes configurations (4 griffes, 6 griffes), travail sur diverses formes de pierres.',
    equipementRequis: ['etabli_sertissage', 'outils_sertissage', 'microscope'],
  },
  {
    codeFormation: 'SERTI_N3',
    nom: 'Sertissage — Niveau 3 Serti Grains',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: 'Niveau 2 serti griffes ou expérience équivalente',
    diplomeDelivre: null,
    tarifStandard: 1330,
    description: 'Stage avancé en sertissage, technique du sertissage à grains. Technique de haute précision.',
    prerequis: ['Avoir suivi le niveau 2 (serti griffes) ou justifier d\'une expérience équivalente'],
    objectifs: [
      'Maîtriser le sertissage à grains',
      'Réaliser des pavages et mises en scène complexes',
      'Atteindre un niveau professionnel en sertissage',
    ],
    programme: 'Sertissage avancé : sertissage à grains, pavé, techniques complexes, réalisation d\'une pièce de haute précision.',
    equipementRequis: ['etabli_sertissage', 'outils_sertissage', 'microscope'],
  },

  // ============================================================
  // CISELURE
  // ============================================================
  {
    codeFormation: 'CISELURE_N1',
    nom: 'Ciselure — Niveau 1 (initiation)',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Initiation à la ciselure : pose de mat, tracé et repoussé.',
    prerequis: [],
    objectifs: [
      'Découvrir les techniques de ciselure',
      'Réaliser des motifs en relief',
    ],
    programme: 'Pose de mat, tracé de motifs, repoussé sur métal.',
    equipementRequis: [],
  },
  {
    codeFormation: 'CISELURE_N2',
    nom: 'Ciselure — Niveau 2 (perfectionnement)',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 ciselure ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Perfectionnement en ciselure : tracé, fond descendu et repoussé.',
    prerequis: ['Niveau 1 ciselure ou compétences équivalentes'],
    objectifs: [
      'Approfondir les techniques de ciselure',
      'Réaliser des reliefs plus complexes',
    ],
    programme: 'Tracé avancé, fond descendu, repoussé profond.',
    equipementRequis: [],
  },
  {
    codeFormation: 'CISELURE_N3',
    nom: 'Ciselure — Niveau 3 (avancé)',
    categorie: 'PERFECTIONNEMENT',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveaux 1 et 2 ciselure',
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Niveau avancé en ciselure : reprise de fonte en ciselure, lancés.',
    prerequis: ['Niveaux 1 et 2 ciselure'],
    objectifs: [
      'Maîtriser les techniques avancées de ciselure',
      'Réaliser des pièces de haute complexité',
    ],
    programme: 'Reprise de fonte en ciselure, lancés, techniques de haute précision.',
    equipementRequis: [],
  },

  // ============================================================
  // ÉMAIL GRAND FEU
  // ============================================================
  {
    codeFormation: 'EMAIL_INITIATION',
    nom: 'Émail grand feu — Initiation (Niveau 1)',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1280,
    description: 'Apprentissage des principales techniques décoratives au choix.',
    prerequis: [],
    objectifs: [
      'Découvrir les techniques de l\'émail grand feu',
      'Réaliser une première pièce émaillée',
    ],
    programme: 'Introduction à l\'émail grand feu : techniques décoratives, cuisson, finitions.',
    equipementRequis: [],
  },
  {
    codeFormation: 'EMAIL_CLOISONNE',
    nom: 'Émail grand feu — Perfectionnement Cloisonné (Niveau 2)',
    categorie: 'PERFECTIONNEMENT',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 émail ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1380,
    description: 'Perfectionnement en émail grand feu : technique du cloisonné au fil ou au ruban.',
    prerequis: ['Niveau 1 émail ou compétences équivalentes'],
    objectifs: ['Maîtriser le cloisonné au fil ou au ruban'],
    programme: 'Cloisonné au fil ou au ruban : préparation, pose des cloisons, remplissage, cuisson.',
    equipementRequis: [],
  },
  {
    codeFormation: 'EMAIL_CHAMPLÈVE',
    nom: 'Émail grand feu — Perfectionnement Champlevé (Niveau 2)',
    categorie: 'PERFECTIONNEMENT',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 émail ou compétences équivalentes',
    diplomeDelivre: null,
    tarifStandard: 1380,
    description: 'Perfectionnement en émail grand feu : technique du champlevé.',
    prerequis: ['Niveau 1 émail ou compétences équivalentes'],
    objectifs: ['Maîtriser le champlevé'],
    programme: 'Champlevé : creusage du métal, remplissage d\'émail, cuisson, polissage.',
    equipementRequis: [],
  },
  {
    codeFormation: 'EMAIL_PLIQUE_A_JOUR',
    nom: 'Émail grand feu — Perfectionnement Plique-à-jour (Niveau 2)',
    categorie: 'PERFECTIONNEMENT',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: 'Niveau 1 émail + formation de base en bijouterie',
    diplomeDelivre: null,
    tarifStandard: 1380,
    description: 'Perfectionnement en émail grand feu : technique du plique-à-jour. Pré-requis : formation de base en bijouterie requise.',
    prerequis: ['Niveau 1 émail', 'Formation de base en bijouterie'],
    objectifs: ['Maîtriser le plique-à-jour'],
    programme: 'Plique-à-jour : construction de l\'armature, remplissage, cuisson, effets translucides.',
    equipementRequis: [],
  },

  // ============================================================
  // GEMMOLOGIE
  // ============================================================
  {
    codeFormation: 'GEMMO_N1',
    nom: 'Gemmologie Appliquée — Niveau 1 Initiation',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1050,
    description: 'Stage d\'initiation à la gemmologie appliquée. Identification et caractérisation des pierres précieuses et fines.',
    prerequis: ['Débutants acceptés', 'CV', 'Questionnaire de positionnement'],
    objectifs: [
      'Connaître les familles de pierres précieuses et fines',
      'Maîtriser les instruments de base en gemmologie',
      'Identifier les principales gemmes',
    ],
    programme: 'Initiation gemmologie : classification des gemmes, cristallographie de base, instruments (loupe, réfractomètre, polariscope), identification des pierres les plus communes.',
    equipementRequis: ['loupe', 'refractometre', 'polariscope', 'microscope', 'salle_cours'],
  },
  {
    codeFormation: 'GEMMO_N2',
    nom: 'Gemmologie de Laboratoire — Niveau 2',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: 'Niveau 1 gemmologie ou expérience équivalente',
    diplomeDelivre: null,
    tarifStandard: 1250,
    description: 'Stage de perfectionnement en gemmologie de laboratoire. Techniques avancées d\'identification et d\'analyse des gemmes.',
    prerequis: ['Avoir suivi le niveau 1 gemmologie ou justifier d\'une expérience équivalente'],
    objectifs: [
      'Utiliser les instruments de laboratoire gemmologique',
      'Identifier des gemmes plus rares ou synthétiques',
      'Détecter les traitements sur les pierres',
    ],
    programme: 'Gemmologie de laboratoire : spectroscope, filtre Chelsea, microscope gemmologique, identification des inclusions, détection des traitements et synthétiques.',
    equipementRequis: ['loupe', 'refractometre', 'polariscope', 'microscope', 'spectroscope', 'salle_cours'],
  },

  // ============================================================
  // TAILLE LAPIDAIRE
  // ============================================================
  {
    codeFormation: 'LAPIDAIRE_N1',
    nom: 'Taille lapidaire — Niveau 1 (cabochon, tailles émeraude et brillant)',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 40,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1630,
    description: 'Initiation à la taille lapidaire : cabochon, tailles émeraude et brillant.',
    prerequis: [],
    objectifs: [
      'Réaliser des cabochons',
      'Maîtriser les tailles émeraude et brillant',
    ],
    programme: 'Introduction à la lapidaire, cabochonnage, taille émeraude, taille brillant.',
    equipementRequis: [],
  },
  {
    codeFormation: 'LAPIDAIRE_N2',
    nom: 'Taille lapidaire — Niveau 2 (tailles ovale et coussin)',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 40,
    dureeJours: null,
    niveauRequis: 'Niveau 1 lapidaire',
    diplomeDelivre: null,
    tarifStandard: 1630,
    description: 'Perfectionnement en taille lapidaire : tailles ovale et coussin.',
    prerequis: ['Niveau 1 lapidaire'],
    objectifs: ['Maîtriser les tailles ovale et coussin'],
    programme: 'Taille ovale, taille coussin, techniques de polissage.',
    equipementRequis: [],
  },
  {
    codeFormation: 'LAPIDAIRE_N3',
    nom: 'Taille lapidaire — Niveau 3 (tailles navette et poire)',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 40,
    dureeJours: null,
    niveauRequis: 'Niveaux 1 et 2 lapidaire',
    diplomeDelivre: null,
    tarifStandard: 1630,
    description: 'Perfectionnement avancé en taille lapidaire : tailles navette et poire.',
    prerequis: ['Niveaux 1 et 2 lapidaire'],
    objectifs: ['Maîtriser les tailles navette et poire'],
    programme: 'Taille navette, taille poire, finitions haute précision.',
    equipementRequis: [],
  },
  {
    codeFormation: 'LAPIDAIRE_N4',
    nom: 'Taille lapidaire — Niveau 4 (retaille, ajustage sur œuvre)',
    categorie: 'PERFECTIONNEMENT',
    dureeHeures: 40,
    dureeJours: null,
    niveauRequis: 'Niveaux 1, 2 et 3 lapidaire',
    diplomeDelivre: null,
    tarifStandard: 1630,
    description: 'Niveau expert en taille lapidaire : retaille et ajustage sur œuvre.',
    prerequis: ['Niveaux 1, 2 et 3 lapidaire'],
    objectifs: ['Maîtriser la retaille et l\'ajustage sur une pièce existante'],
    programme: 'Retaille, ajustage sur œuvre, corrections et retouches de haute précision.',
    equipementRequis: [],
  },

  // ============================================================
  // ATELIERS DÉCOUVERTE (transversaux)
  // ============================================================
  {
    codeFormation: 'ATD_BIJ_EMAIL',
    nom: 'Atelier découverte — Bijouterie & émail grand feu',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage de découverte transversal : réalisation d\'un projet de bijou comportant de la bijouterie et de l\'émail grand feu.',
    prerequis: [],
    objectifs: ['Combiner bijouterie et émail sur un projet unique'],
    programme: 'Projet de bijou combinant techniques de bijouterie et d\'émail grand feu.',
    equipementRequis: [],
  },
  {
    codeFormation: 'ATD_BIJ_LAPIDAIRE',
    nom: 'Atelier découverte — Bijouterie & taille lapidaire',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage de découverte transversal : projet de bijou combinant bijouterie et lapidaire (cabochon taillé mis en valeur sur le bijou).',
    prerequis: [],
    objectifs: ['Réaliser un bijou intégrant une pierre taillée'],
    programme: 'Projet de bijou : bijouterie + lapidaire pour cabochon en gemme.',
    equipementRequis: [],
  },
  {
    codeFormation: 'ATD_CISELURE_EMAIL',
    nom: 'Atelier découverte — Ciselure & émail grand feu',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 1130,
    description: 'Stage de découverte transversal : ciselure pour texturage sur métal + émail grand feu.',
    prerequis: [],
    objectifs: ['Combiner ciselure et émail sur une pièce commune'],
    programme: 'Pièce commune : ciselure pour effet de texturage + émail grand feu.',
    equipementRequis: [],
  },

  // ============================================================
  // MODULES THÉORIQUES / CULTURE BIJOUTERIE
  // ============================================================
  {
    codeFormation: 'HISTOIRE_ART',
    nom: 'Histoire de l\'art du bijou',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 900,
    description: 'Histoire des arts bijoutiers en présentiel — de la Préhistoire à nos jours. Évolution stylistique et techniques du bijou, analyse stylistique.',
    prerequis: [],
    objectifs: [
      'Connaître l\'histoire du bijou à travers les époques',
      'Analyser les styles et techniques historiques',
    ],
    programme: 'Bijoux de la Préhistoire à l\'Antiquité, Moyen-Âge, Renaissance, XVIIe-XIXe s., Art Nouveau, Art Déco, design contemporain.',
    equipementRequis: [],
  },
  {
    codeFormation: 'DESSIN_TECHNIQUE',
    nom: 'Pratiques du dessin — Dessin technique',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: null,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 900,
    description: 'Module de dessin technique intégré à la préparation CAP ATBJ. Représentation technique des bijoux.',
    prerequis: [],
    objectifs: ['Maîtriser le dessin technique appliqué à la bijouterie'],
    programme: 'Dessin technique : vues, coupes, cotation, représentation bijoux.',
    equipementRequis: [],
  },
  {
    codeFormation: 'DESSIN_GOUACHE',
    nom: 'Dessin de Bijoux Gouaché — Pratiques du Dessin',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 30,
    dureeJours: 4,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 900,
    description: 'Formation au dessin de bijoux gouaché. Représentation fidèle des matières : métaux, pierres, perles. Module intégré à la préparation CAP ATBJ.',
    prerequis: ['Tous publics'],
    objectifs: [
      'Maîtriser la technique du gouaché appliqué aux bijoux',
      'Représenter fidèlement les métaux, pierres et perles',
      'Créer des rendus professionnels de bijoux',
    ],
    programme: 'Gouaché bijouterie : matériaux et pigments, techniques de rendu des métaux (or, argent, platine), pierres précieuses (diamant, rubis, émeraude), perles et matières organiques. Réalisation de rendus complets.',
    equipementRequis: ['salle_cours', 'materiel_dessin'],
  },
  {
    codeFormation: 'DOUANE_GARANTIE',
    nom: 'Douane & Garantie — Univers de l\'Entreprise',
    categorie: 'FORMATION_COURTE',
    dureeHeures: 4,
    dureeJours: 1,
    niveauRequis: null,
    diplomeDelivre: null,
    tarifStandard: 180,
    description: 'Formation courte sur la législation douanière et le système de garantie en bijouterie-joaillerie. Indispensable pour les entrepreneurs et artisans.',
    prerequis: ['Professionnels ou futurs créateurs d\'entreprise'],
    objectifs: [
      'Comprendre la réglementation douanière en bijouterie',
      'Connaître les poinçons et le système de garantie',
      'Maîtriser les obligations légales pour exercer',
    ],
    programme: 'Douane : réglementation importation/exportation des métaux précieux et pierres. Garantie : poinçons de maître, poinçons de titre, poinçons d\'importation, contrôle du bureau de garantie, obligations légales.',
    equipementRequis: ['salle_cours'],
  },
]

async function main() {
  console.log('Seed formations ABJ — 40 formations officielles\n')

  let updated = 0
  let created = 0

  for (const f of formations) {
    const result = await prisma.formation.upsert({
      where: { codeFormation: f.codeFormation },
      update: {
        nom: f.nom,
        categorie: f.categorie,
        dureeHeures: f.dureeHeures,
        dureeJours: f.dureeJours,
        niveauRequis: f.niveauRequis,
        diplomeDelivre: f.diplomeDelivre,
        tarifStandard: f.tarifStandard,
        description: f.description,
        prerequis: f.prerequis,
        objectifs: f.objectifs,
        programme: f.programme,
        equipementRequis: f.equipementRequis,
      },
      create: {
        codeFormation: f.codeFormation,
        nom: f.nom,
        categorie: f.categorie,
        dureeHeures: f.dureeHeures,
        dureeJours: f.dureeJours,
        niveauRequis: f.niveauRequis,
        diplomeDelivre: f.diplomeDelivre,
        tarifStandard: f.tarifStandard,
        description: f.description,
        prerequis: f.prerequis,
        objectifs: f.objectifs,
        programme: f.programme,
        equipementRequis: f.equipementRequis,
      },
    })
    console.log(`  ✓ ${f.codeFormation} — ${f.nom}`)
    updated++
  }

  const total = await prisma.formation.count()
  console.log(`\n✅ ${updated} formations upsertées — Total en base : ${total}`)

  await prisma.$disconnect()
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
